# ============================================================
# IDS — Politique de Sécurité (Système Allow/Deny Cumulatif)
# Format : username;resource;policy_type;task;start_date;end_date;active
# Type   : allow (autoriser) ou deny (refuser)
# Dates  : YYYY-MM-DD ou YYYY-MM-DD HH:MM
# Active : 1=oui, 0=non
# Tâches : read, write, delete, execute, admin, login,
#          failed_login, backup, network_access
# ============================================================

alice;ssh_server;allow;login;2026-01-01;2026-12-31;1
alice;ssh_server;allow;execute;2026-01-01;2026-12-31;1
alice;file_system;allow;read;2026-01-01;2026-12-31;1
alice;file_system;allow;write;2026-01-01;2026-12-31;1
alice;user_management;allow;read;2026-01-01;2026-12-31;1
alice;database;allow;read;2026-01-01;2026-12-31;1
alice;database;allow;write;2026-01-01;2026-12-31;1
alice;backup;allow;backup;2026-01-01;2026-12-31;1
alice;network_access;allow;login;2026-01-01;2026-12-31;1
bob;ssh_server;allow;login;2026-01-01;2026-12-31;1
bob;file_system;allow;read;2026-01-01;2026-12-31;1
bob;database;allow;read;2026-01-01;2026-06-30;1
bob;network_access;allow;login;2026-01-01;2026-12-31;1
charlie;ssh_server;allow;login;2026-01-01;2026-12-31;1
charlie;ssh_server;deny;execute;2026-01-01;2026-12-31;1
charlie;file_system;allow;write;2026-01-01;2026-12-31;1
charlie;network_access;allow;login;2026-01-01;2026-12-31;1
roberto;ssh_server;allow;login;2026-01-01;2026-12-31;1
roberto;ssh_server;allow;admin;2026-01-01;2026-12-31;1
roberto;network_access;allow;login;2026-01-01;2026-12-31;1
root;ssh_server;allow;login;2026-01-01;2026-12-31;1
root;ssh_server;allow;admin;2026-01-01;2026-12-31;1
root;file_system;allow;delete;2026-01-01;2026-12-31;1
root;file_system;allow;read;2026-01-01;2026-12-31;1
root;file_system;allow;write;2026-01-01;2026-12-31;1
root;user_management;allow;admin;2026-01-01;2026-12-31;1
root;backup;allow;backup;2026-01-01;2026-12-31;1
root;backup;allow;restore;2026-01-01;2026-12-31;1
root;network_access;allow;login;2026-01-01;2026-12-31;1
